[package]
name = "x402_zk_credential"
type = "bin"
authors = ["Rank One Labs"]
compiler_version = ">=1.0.0"

[dependencies]
poseidon = { tag = "v0.2.3", git = "https://github.com/noir-lang/poseidon" }
